import type { Product } from "./types"

export const mockProducts: Product[] = [
  // Шаурма
  {
    id: "shawarma-pork-470",
    name: "Шаурма со свининой",
    description: "Сочная свинина, свежие овощи, фирменный соус",
    category: "shawarma",
    image: "/delicious-shawarma-wrap-with-chicken-and-vegetable.jpg",
    basePrice: 250,
    variants: [
      { id: "small", name: "270гр", price: 250 },
      { id: "large", name: "470гр", price: 310, priceModifier: 60 },
    ],
    available: true,
  },
  {
    id: "shawarma-pork-cheese",
    name: "Шаурма со свининой и сыром",
    description: "Свинина с расплавленным сыром",
    category: "shawarma",
    image: "/beef-shawarma-with-pickles-and-sauce.jpg",
    basePrice: 270,
    variants: [
      { id: "small", name: "240гр", price: 270 },
      { id: "large", name: "440гр", price: 330, priceModifier: 60 },
    ],
    available: true,
  },
  {
    id: "shawarma-chicken",
    name: "Шаурма с куриным филе",
    description: "Нежное куриное филе, овощи, соус",
    category: "shawarma",
    image: "/delicious-shawarma-wrap-with-chicken-and-vegetable.jpg",
    basePrice: 230,
    variants: [
      { id: "small", name: "270гр", price: 230 },
      { id: "large", name: "470гр", price: 290, priceModifier: 60 },
    ],
    available: true,
  },
  {
    id: "shawarma-chicken-cheese",
    name: "Шаурма с куриным филе и сыром",
    description: "Курица с сыром",
    category: "shawarma",
    image: "/delicious-shawarma-wrap-with-chicken-and-vegetable.jpg",
    basePrice: 260,
    variants: [
      { id: "small", name: "240гр", price: 260 },
      { id: "large", name: "440гр", price: 310, priceModifier: 50 },
    ],
    available: true,
  },
  {
    id: "shawarma-ham",
    name: "Шаурма с ветчиной",
    description: "Ветчина, овощи, соус",
    category: "shawarma",
    image: "/beef-shawarma-with-pickles-and-sauce.jpg",
    basePrice: 220,
    variants: [
      { id: "small", name: "270гр", price: 220 },
      { id: "large", name: "470гр", price: 260, priceModifier: 40 },
    ],
    available: true,
  },
  {
    id: "shawarma-sausage",
    name: "Шаурма с молочной сосиской",
    description: "Молочная сосиска, овощи",
    category: "shawarma",
    image: "/delicious-shawarma-wrap-with-chicken-and-vegetable.jpg",
    basePrice: 250,
    variants: [{ id: "regular", name: "450гр", price: 250 }],
    available: true,
  },
  {
    id: "shawarma-veg",
    name: "Шаурма со свежими овощами",
    description: "Только свежие овощи",
    category: "shawarma",
    image: "/vegetarian-falafel-shawarma-wrap.jpg",
    basePrice: 220,
    variants: [{ id: "regular", name: "420гр", price: 220 }],
    available: true,
  },
  {
    id: "brtuch-pork",
    name: "Бртуч со свининой, сыром и свежими овощами",
    description: "450гр",
    category: "shawarma",
    image: "/beef-shawarma-with-pickles-and-sauce.jpg",
    basePrice: 340,
    available: true,
  },
  {
    id: "brtuch-chicken",
    name: "Бртуч с курицей, сыром и свежими овощами",
    description: "450г",
    category: "shawarma",
    image: "/delicious-shawarma-wrap-with-chicken-and-vegetable.jpg",
    basePrice: 330,
    available: true,
  },
  {
    id: "brtuch-ham",
    name: "Бртуч с ветчиной, сыром и свежими овощами",
    description: "450г",
    category: "shawarma",
    image: "/beef-shawarma-with-pickles-and-sauce.jpg",
    basePrice: 290,
    available: true,
  },
  {
    id: "village-chicken",
    name: "Деревенская с курицей",
    description: "480гр",
    category: "shawarma",
    image: "/delicious-shawarma-wrap-with-chicken-and-vegetable.jpg",
    basePrice: 360,
    available: true,
  },
  {
    id: "village-pork",
    name: "Деревенская со свининой",
    description: "480гр",
    category: "shawarma",
    image: "/beef-shawarma-with-pickles-and-sauce.jpg",
    basePrice: 370,
    available: true,
  },
  {
    id: "shawarma-hawaiian",
    name: "Шаурма Гавайская",
    description: "С тропическими нотками",
    category: "shawarma",
    image: "/delicious-shawarma-wrap-with-chicken-and-vegetable.jpg",
    basePrice: 330,
    available: true,
  },
  {
    id: "shawarma-italian",
    name: "Шаурма Итальянская",
    description: "В итальянском стиле",
    category: "shawarma",
    image: "/beef-shawarma-with-pickles-and-sauce.jpg",
    basePrice: 350,
    available: true,
  },
  {
    id: "shawarma-mushroom",
    name: "Шаурма Грибная",
    description: "С грибами",
    category: "shawarma",
    image: "/vegetarian-falafel-shawarma-wrap.jpg",
    basePrice: 350,
    available: true,
  },

  // Хот-доги
  {
    id: "hotdog-french",
    name: "Хот-дог французкий с Куриной колбаской",
    description: "Французский стиль",
    category: "hotdogs",
    image: "/crispy-french-fries.png",
    basePrice: 200,
    available: true,
  },
  {
    id: "hotdog-danish",
    name: "Хот-дог дацкий с охотничьей колбаской",
    description: "Датский стиль",
    category: "hotdogs",
    image: "/crispy-french-fries.png",
    basePrice: 230,
    available: true,
  },

  // Картофель фри и другое
  {
    id: "fries",
    name: "Картофель фри",
    description: "150 гр",
    category: "sides",
    image: "/crispy-french-fries.png",
    basePrice: 250,
    available: true,
  },
  {
    id: "nuggets",
    name: "Наггетсы",
    description: "Хрустящие куриные наггетсы",
    category: "sides",
    image: "/crispy-french-fries.png",
    basePrice: 250,
    available: true,
  },
  {
    id: "chickenburger",
    name: "Чикенбургер",
    description: "Сочный бургер с курицей",
    category: "sides",
    image: "/crispy-french-fries.png",
    basePrice: 280,
    available: true,
  },

  // Кофе
  {
    id: "coffee",
    name: "Кофе 3в1",
    description: "200мл",
    category: "drinks",
    image: "/coca-cola-drink-glass.jpg",
    basePrice: 60,
    available: true,
  },

  // Добавки
  {
    id: "addon-chicken",
    name: "Курица",
    description: "Добавка",
    category: "addons",
    image: "/delicious-shawarma-wrap-with-chicken-and-vegetable.jpg",
    basePrice: 80,
    available: true,
  },
  {
    id: "addon-pork",
    name: "Свинина",
    description: "Добавка",
    category: "addons",
    image: "/beef-shawarma-with-pickles-and-sauce.jpg",
    basePrice: 90,
    available: true,
  },
  {
    id: "addon-pepperoni",
    name: "Колбаска пепперони",
    description: "Добавка",
    category: "addons",
    image: "/crispy-french-fries.png",
    basePrice: 70,
    available: true,
  },
  {
    id: "addon-mushrooms",
    name: "Шампиньоны жареные",
    description: "Добавка",
    category: "addons",
    image: "/crispy-french-fries.png",
    basePrice: 80,
    available: true,
  },
  {
    id: "addon-pineapple",
    name: "Ананасы",
    description: "Добавка",
    category: "addons",
    image: "/crispy-french-fries.png",
    basePrice: 75,
    available: true,
  },
  {
    id: "addon-pickles",
    name: "Маринованные огурцы",
    description: "Добавка",
    category: "addons",
    image: "/crispy-french-fries.png",
    basePrice: 50,
    available: true,
  },
  {
    id: "addon-carrot",
    name: "Корейская морковь",
    description: "Добавка",
    category: "addons",
    image: "/crispy-french-fries.png",
    basePrice: 40,
    available: true,
  },
]

export const categories = [
  { id: "shawarma", name: "Шаурма" },
  { id: "hotdogs", name: "Хот-доги" },
  { id: "sides", name: "Картофель фри" },
  { id: "drinks", name: "Кофе" },
  { id: "addons", name: "Добавки" },
] as const
